name: Auto Sync Repo
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install requests
          sudo apt update && sudo apt install -y apt-utils
      - name: Run sync script
        run: python3 sync.py
      - name: Commit & Push update
        run: |
          git config --global user.name "rptk0"
          git config --global user.email "rptk0@users.noreply.github.com"
          git add .
          git commit -m "Auto sync all sources" || echo "No changes to commit"
          git push
